# Implement Union, Intersection, Complement and Difference operations on fuzzy sets. Also create fuzzy relations by Cartesian product of any two fuzzy sets and perform max-min composition on any two fuzzy relations.

In [ ]:
import numpy as np

# Fuzzy Sets
A = np.array([0.2, 0.5, 0.7])
B = np.array([0.4, 0.3, 0.8])

# Operations
print("Union:", np.maximum(A, B))
print("Intersection:", np.minimum(A, B))
print("Complement of A:", 1 - A)
print("Difference A-B:", np.minimum(A, 1 - B))

# Cartesian Product Relations
R = np.minimum.outer(A, B)
C = np.array([0.1, 0.9, 0.5])
S = np.minimum.outer(B, C)

print("\nRelation R:\n", R)
print("\nRelation S:\n", S)

# Max-Min Composition
T = np.array([[max(min(R[i][k], S[k][j])
          for k in range(len(B)))
          for j in range(len(C))]
          for i in range(len(A))])

print("\nMax-Min Composition:\n", T)

Union: [0.4 0.5 0.8]
Intersection: [0.2 0.3 0.7]
Complement of A: [0.8 0.5 0.3]
Difference A-B: [0.2 0.5 0.2]

Relation R:
 [[0.2 0.2 0.2]
 [0.4 0.3 0.5]
 [0.4 0.3 0.7]]

Relation S:
 [[0.1 0.4 0.4]
 [0.1 0.3 0.3]
 [0.1 0.8 0.5]]

Max-Min Composition:
 [[0.1 0.2 0.2]
 [0.1 0.5 0.5]
 [0.1 0.7 0.5]]
